spring:
  datasource:
    url: jdbc:mariadb://172.17.0.1:3306/file_upload_prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: Aruminglocal
    password: Aruming1234
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    com.ll.exam.sb_file_upload.app: info
custom:
  genFileDirPath: /gen